<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <!-- Constants that can be overriden by skin generator -->
  <VARIABLE id="display_levels_default" value="1"/>
  <VARIABLE id="display_script_title_default" value="1"/>
  <VARIABLE id="display_status_bar_default" value="1"/>
  <VARIABLE id="display_handles_default" value="1"/>
  <VARIABLE id="display_screws_default" value="1"/>
  <VARIABLE id="display_logo_default" value="1"/>
  <VARIABLE id="background_style_default" value="0"/>
</DUMMY>