<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <!-- Constants that can be overriden by skin generator -->
  <VARIABLE id="display_levels_default" value="#display_levels#"/>
  <VARIABLE id="display_script_title_default" value="#display_script_title#"/>
  <VARIABLE id="display_status_bar_default" value="#display_status_bar#"/>
  <VARIABLE id="display_handles_default" value="#display_handles#"/>
  <VARIABLE id="display_screws_default" value="#display_screws#"/>
  <VARIABLE id="display_logo_default" value="#display_logo#"/>
  <VARIABLE id="background_style_default" value="#background_style_default#"/>
</DUMMY>