<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <LOCAL_VARIABLE id="CURRENT_DIR" value="$_DIR_$"/>
  <DEFINE>
    <PNS_DASHED_GROUP_BOX base_type="IMAGE_GROUP_BOX" image="$CURRENT_DIR$/FORK_LARGE.png" ignore_mask_files="true"/>
    <PNS_PLAIN_GROUP_BOX base_type="IMAGE_GROUP_BOX" image="$CURRENT_DIR$/FORK_LARGE.png" image_top_left="$CURRENT_DIR$/plain_top_left.png" image_top_right="$CURRENT_DIR$/plain_top_right.png" image_bottom_left="$CURRENT_DIR$/plain_bottom_left.png" image_bottom_right="$CURRENT_DIR$/plain_bottom_right.png" ignore_mask_files="true"/>
    <PNS_FILLED_GROUP_BOX base_type="IMAGE_GROUP_BOX" image="$CURRENT_DIR$/full.png" ignore_mask_files="true" opacity="50%"/>
    <PNS_LCD_GROUP_BOX base_type="THEME_GRAPH_BOX" h_margin="8" v_margin="8"/>
  </DEFINE>
</DUMMY>