<?xml version="1.0" encoding="utf-8" ?>
<DEFINE>
  <!-- toolbar buttons -->
  <CUS_SHOW_CONTROLS_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/show_controls_button.png" image_focus="$_DIR_$/show_controls_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_SHOW_KNOBS_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/show_knobs_button.png" image_focus="$_DIR_$/show_knobs_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_SHOW_GRAPH_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/show_graph_button.png" image_focus="$_DIR_$/show_graph_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_SHOW_PREFS_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/show_prefs_button.png" image_focus="$_DIR_$/show_prefs_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_SHOW_METERS_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/show_meters_button.png" image_focus="$_DIR_$/show_meters_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_SHOW_BROWSER_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/browser.png" image_focus="$_DIR_$/browser_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_SHOW_MAP_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/target.png" image_focus="$_DIR_$/target_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_TOOLBAR_LOCK_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/lock_button.png" image_focus="$_DIR_$/lock_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_MAGNIFY_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/magnifier_button.png" image_focus="$_DIR_$/magnifier_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_REFRESH_PARAM_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$_DIR_$/refresh_button.png" image_focus="$_DIR_$/refresh_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" images_count="1" positions_count="2" image_scaling=".5"/>
  <CUS_EDIT_ACTION_BUTTON base_type="IMAGE_ACTION_BUTTON" image="$_DIR_$/edit_button.png" image_focus="$_DIR_$/edit_button_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
  <CUS_CLEAN_ACTION_BUTTON base_type="IMAGE_ACTION_BUTTON" image="$_DIR_$/clean.png" image_focus="$_DIR_$/clean_hover.png" opaque_mouse_mask="true" cursor="system::hand" image_scaling=".5"/>
</DEFINE>