<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <LOCAL_VARIABLE id="CURRENT_DIR" value="$_DIR_$"/>
  <DEFINE>
    <PNS_JOYSTICK base_type="XYZ_IMAGE_PARAM_JOYSTICK" thumb_image="$CURRENT_DIR$/joystick_thumb.png" image_mouse_mask="" ignore_mask_file="true" cursor="system::hand"/>
    <PNS_VINTAGE_SWITCH base_type="IMAGE_PARAM_BUTTON" image="$CURRENT_DIR$/vintage_switch.png" ignore_mask_files="true" cursor="system::hand"/>
    <PNS_CLASSIC_SWITCH  base_type="THEME_ON_OFF_SWITCH" cursor="system::hand"/>
    <PNS_VSELECT_SWITCH  base_type="THEME_V_SELECT_SWITCH" cursor="system::hand"/>
    <PNS_HSELECT_SWITCH  base_type="THEME_H_SELECT_SWITCH" cursor="system::hand"/>
    <PNS_DROPDOWN_ARROW  base_type="IMAGE" image="$CURRENT_DIR$/arrow.png" ignore_mask_files="true"/>
  </DEFINE>
</DUMMY>