<?xml version="1.0" encoding="utf-8" ?> 
<DEFINE>
<CUS_FADER base_type="IMAGE_PARAM_SLIDER" image="$THEME_PATH$/sliders/fader_channel.png" image_mouse_mask="" thumb_image="$THEME_PATH$/sliders/fader_thumb.png" cursor="system::hand" positions_count="81" thumb_h_center="8" thumb_v_center="16" offset=".5" margin_before="3" margin_after="3"/>
<CUS_FADER_SLIM base_type="IMAGE_PARAM_SLIDER" image="$THEME_PATH$/sliders/fader_channel.png" image_mouse_mask="" thumb_image="$THEME_PATH$/sliders/fader_thumb_slim.png" cursor="system::hand" positions_count="81" thumb_h_center="7" thumb_v_center="16" offset=".5" margin_before="3" margin_after="3"/>
</DEFINE>