<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <LOCAL_VARIABLE id="CURRENT_DIR" value="$_DIR_$"/>
  <DEFINE>
    <!-- *********** LIGHT BACKGROUND ***********  -->
    <!-- sliver and gold knobs -->
    <PNS_GOLD_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/gold_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_KNOB_SYM base_type="PNS_GOLD_KNOB"/>
    <PNS_SILVER_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/silver_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_KNOB_SYM base_type="PNS_SILVER_KNOB"/>

    <!-- Chicken head knobs -->
    <PNS_BLACK_CHICKEN_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_chicken_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_CHICKEN_KNOB_SYM base_type="PNS_BLACK_CHICKEN_KNOB"/>
    <PNS_WHITE_CHICKEN_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/white_chicken_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_WHITE_CHICKEN_KNOB_SYM base_type="PNS_WHITE_CHICKEN_KNOB"/>
    <PNS_CREAM_CHICKEN_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/cream_chicken_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_CREAM_CHICKEN_KNOB_SYM base_type="PNS_CREAM_CHICKEN_KNOB"/>

    <!-- Skirted knobs -->
    <PNS_BLACK_SKIRTED_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_skirted_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_SKIRTED_KNOB_SYM base_type="PNS_BLACK_SKIRTED_KNOB"/>

    <!-- Vintage knobs -->
    <PNS_BLACK_VINTAGE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_vintage_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_VINTAGE_KNOB_SYM base_type="PNS_BLACK_VINTAGE_KNOB"/>

    <!-- *********** DARK BACKGROUND ************* -->
    <!-- sliver and gold knobs -->
    <PNS_GOLD_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/gold_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_B_KNOB_SYM base_type="PNS_GOLD_B_KNOB"/>
    <PNS_SILVER_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/silver_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_B_KNOB_SYM base_type="PNS_SILVER_B_KNOB"/>

    <!-- Chicken head knobs -->
    <PNS_BLACK_CHICKEN_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_chicken_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_CHICKEN_B_KNOB_SYM base_type="PNS_BLACK_CHICKEN_B_KNOB"/>
    <PNS_WHITE_CHICKEN_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/white_chicken_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_WHITE_CHICKEN_B_KNOB_SYM base_type="PNS_WHITE_CHICKEN_B_KNOB"/>
    <PNS_CREAM_CHICKEN_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/cream_chicken_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_CREAM_CHICKEN_B_KNOB_SYM base_type="PNS_CREAM_CHICKEN_B_KNOB"/>
    <!-- Vintage knobs -->
    <PNS_BLACK_VINTAGE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_vintage_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_VINTAGE_B_KNOB_SYM base_type="PNS_BLACK_VINTAGE_B_KNOB"/>

    <!-- Skirted knobs -->
    <PNS_BLACK_SKIRTED_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_skirted_knob_b.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_SKIRTED_B_KNOB_SYM base_type="PNS_BLACK_SKIRTED_B_KNOB"/>

    <!-- ************ NEUTRAL *************  -->
    <PNS_BLACK_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_stove_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_STOVE_KNOB_SYM base_type="PNS_BLACK_STOVE_KNOB"/>
    <PNS_WHITE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/white_stove_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_WHITE_STOVE_KNOB_SYM base_type="PNS_WHITE_STOVE_KNOB"/>
    <PNS_ORANGE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/orange_stove_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_ORANGE_STOVE_KNOB_SYM base_type="PNS_ORANGE_STOVE_KNOB"/>
    <PNS_BLACKORANGE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black-orange_stove_knob.png" images_count="147" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACKORANGE_STOVE_KNOB_SYM base_type="PNS_BLACKORANGE_STOVE_KNOB"/>
    <PNS_BLUE_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/blue_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_BLUE_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/blue_flat_knob_sym.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_GREY_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/grey_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_GREY_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/grey_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_ORANGE_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/orange_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_ORANGE_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/orange_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_YELLOW_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/yellow_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_YELLOW_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/yellow_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_GREEN_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/green_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_GREEN_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/green_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_RED_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/red_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_RED_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/red_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>

    <!-- ************ FROM BCA DEFAULT THEME *************  -->
    <PNS_SILVER_BLUE_MODERN_KNOB base_type="THEME_KNOB_CHANNEL1"/>
    <PNS_SILVER_BLUE_MODERN_KNOB_SYM base_type="THEME_KNOB_CHANNEL1_SYM"/>
    <PNS_SILVER_PINK_MODERN_KNOB base_type="THEME_KNOB_CHANNEL2"/>
    <PNS_SILVER_PINK_MODERN_KNOB_SYM base_type="THEME_KNOB_CHANNEL2_SYM"/>
    <PNS_BLACK_BLUE_MODERN_KNOB base_type="THEME_ALT_KNOB_CHANNEL1"/>
    <PNS_BLACK_BLUE_MODERN_KNOB_SYM base_type="THEME_ALT_KNOB_CHANNEL1_SYM"/>
    <PNS_BLACK_PINK_MODERN_KNOB base_type="THEME_ALT_KNOB_CHANNEL2"/>
    <PNS_BLACK_PINK_MODERN_KNOB_SYM base_type="THEME_ALT_KNOB_CHANNEL2_SYM"/>
  </DEFINE>
</DUMMY>